//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HashGagAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tweet
    {
        public int HashgagTweetID { get; set; }
        public Nullable<long> TweetID { get; set; }
        public Nullable<long> TwitterUserID { get; set; }
        public Nullable<System.DateTimeOffset> CreatedAt { get; set; }
        public Nullable<int> FavouriteCount { get; set; }
        public Nullable<bool> Favourited { get; set; }
        public string IDString { get; set; }
        public string InReplyToScreenName { get; set; }
        public Nullable<long> InReplyToStatusID { get; set; }
        public string InReplyToStatusIDString { get; set; }
        public Nullable<long> InReplyToUserID { get; set; }
        public string InReplyToUserIDString { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Long { get; set; }
        public Nullable<int> RetweetCount { get; set; }
        public Nullable<bool> Retweeted { get; set; }
        public string Text { get; set; }
    }
}
