//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HashGag.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TwitterUser
    {
        public TwitterUser()
        {
            this.CompetitionTweets = new HashSet<CompetitionTweet>();
            this.Questions = new HashSet<Question>();
            this.Tweets = new HashSet<Tweet>();
        }
    
        public int HashgagUserID { get; set; }
        public long TwitterID { get; set; }
        public System.DateTimeOffset CreatedAt { get; set; }
        public bool DefaultProfile { get; set; }
        public bool DefaultProfileImage { get; set; }
        public string Description { get; set; }
        public Nullable<int> FavouritesCount { get; set; }
        public int FollowersCount { get; set; }
        public int FriendsCount { get; set; }
        public bool GeoEnabled { get; set; }
        public string IDStr { get; set; }
        public int ListedCount { get; set; }
        public string Location { get; set; }
        public string Name { get; set; }
        public string ProfileImageURL { get; set; }
        public string ProfileImageURLHttps { get; set; }
        public bool Protected { get; set; }
        public string ScreenName { get; set; }
        public int StatusesCount { get; set; }
        public string TimeZone { get; set; }
        public string URL { get; set; }
        public Nullable<int> UtcOffset { get; set; }
        public bool Verified { get; set; }
    
        public virtual ICollection<CompetitionTweet> CompetitionTweets { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
        public virtual ICollection<Tweet> Tweets { get; set; }
    }
}
