//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HashGag.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TwitterUser
    {
        public TwitterUser()
        {
            this.CompetitionTweets = new HashSet<CompetitionTweet>();
            this.Questions = new HashSet<Question>();
        }
    
        public int HashgagUserID { get; set; }
        public long TwitterID { get; set; }
        public System.DateTimeOffset CreatedAt { get; set; }
        public string Description { get; set; }
        public Nullable<int> FavouritesCount { get; set; }
        public Nullable<int> FollowersCount { get; set; }
        public Nullable<int> FriendsCount { get; set; }
        public string IDStr { get; set; }
        public Nullable<int> ListedCount { get; set; }
        public string Location { get; set; }
        public string Name { get; set; }
        public string ProfileImageURL { get; set; }
        public string ProfileImageURLHttps { get; set; }
        public string ScreenName { get; set; }
        public Nullable<int> StatusesCount { get; set; }
    
        public virtual ICollection<CompetitionTweet> CompetitionTweets { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
    }
}
