//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Twitter_Engine.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hashgagEntities : DbContext
    {
        public hashgagEntities()
            : base("name=hashgagEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CompetitionTweet> CompetitionTweets { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<TwitterUser> TwitterUsers { get; set; }
        public virtual DbSet<Tweet> Tweets { get; set; }
    }
}
